import { Category } from "../model/Item";

export const mostCommons = [
  {
    id: Math.random(),
    name: "Fiocchi d'avena",
    heart: false,
    category: Category.CEREALI,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Latte vegetale",
    heart: false,
    category: Category.LATTICINI,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Frutti di bosco freschi o surgelati",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Noci",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "The verde",
    heart: false,
    category: Category.ALTRO,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Yogurt greco",
    heart: false,
    category: Category.LATTICINI,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Frutta fresca",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Insalata fresca",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Pomodori",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Cetrioli",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Peperoni",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Avocado",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Pollo",
    heart: false,
    category: Category.CARNE_PESCE,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Pane integrale",
    heart: false,
    category: Category.PANIFICIO,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Carote",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Sedano",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Patate",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Patate dolci",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Salmone",
    heart: false,
    category: Category.CARNE_PESCE,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Asparagi",
    heart: false,
    category: Category.FRUTTA_VERDURA,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Aceto",
    heart: false,
    category: Category.ALTRO,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Pasta Integrale",
    heart: false,
    category: Category.PASTA_RISO,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Uova",
    heart: false,
    category: Category.CARNE_PESCE,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Riso basmati",
    heart: false,
    category: Category.PASTA_RISO,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Acqua",
    heart: false,
    category: Category.ALTRO,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Carta igenica",
    heart: false,
    category: Category.ALTRO,
    owned: false,
  },
  {
    id: Math.random(),
    name: "Scottex",
    heart: false,
    category: Category.ALTRO,
    owned: false,
  },
];
